version: '3'

services:
  php:
    build: ./docker/php
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    volumes: [ './:/var/www/symfony:cached' ]
    networks:
      - web
      - default

  nginx:
    build: ./docker/nginx
    volumes: [ './:/var/www/symfony:cached' ]
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:${HOST_URL}"
      - "traefik.basic.port=80"
      - "traefik.basic.protocol=http"
    networks:
      - web
      - default
    ports:
      - "8000:80"

networks:
  web:
    external: true
